
package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISendMsgWebServiceService", targetNamespace = "http://webservice.service.sms.com/", wsdlLocation = "http://localhost:8080/sms/services/sendMsg?wsdl")
public class ISendMsgWebServiceService
    extends Service
{

    private final static URL ISENDMSGWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ISENDMSGWEBSERVICESERVICE_EXCEPTION;
    private final static QName ISENDMSGWEBSERVICESERVICE_QNAME = new QName("http://webservice.service.sms.com/", "ISendMsgWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sms/services/sendMsg?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISENDMSGWEBSERVICESERVICE_WSDL_LOCATION = url;
        ISENDMSGWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ISendMsgWebServiceService() {
        super(__getWsdlLocation(), ISENDMSGWEBSERVICESERVICE_QNAME);
    }

    public ISendMsgWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISENDMSGWEBSERVICESERVICE_QNAME, features);
    }

    public ISendMsgWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ISENDMSGWEBSERVICESERVICE_QNAME);
    }

    public ISendMsgWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISENDMSGWEBSERVICESERVICE_QNAME, features);
    }

    public ISendMsgWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISendMsgWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISendMsgWebService
     */
    @WebEndpoint(name = "ISendMsgWebServicePort")
    public ISendMsgWebService getISendMsgWebServicePort() {
        return super.getPort(new QName("http://webservice.service.sms.com/", "ISendMsgWebServicePort"), ISendMsgWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISendMsgWebService
     */
    @WebEndpoint(name = "ISendMsgWebServicePort")
    public ISendMsgWebService getISendMsgWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.service.sms.com/", "ISendMsgWebServicePort"), ISendMsgWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISENDMSGWEBSERVICESERVICE_EXCEPTION!= null) {
            throw ISENDMSGWEBSERVICESERVICE_EXCEPTION;
        }
        return ISENDMSGWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
