var _REQHOST="";
var _IMG_PRIVATE=_REQHOST+"/i/lock.gif";
var _IMG_FAVONLY=_REQHOST+"/i/smiley1.gif";
var _CALENDAR_REQMODE='';

var _DAYVIEW=0;
var _WEEKVIEW=1;
var _MONTHVIEW=2;

var _CELLHEIGHTPX=25;
var _CELLWIDTHPX=75;
var _CELLMONTHWIDTHPX=150;
var _CELLMONTHHEIGHTPX=75;
var _MARGIN=5;

var _12HOURCLOCK=0;
var _24HOURCLOCK=1;
var _12HOURSHORT=2;
var _CLOCK=null;

var _DATE_DDMMYYYY=0;
var _DATE_MMDDYYYY=1;
var _DATE_YYYYMMDD=5;
var _DATE_MNAMEDYYYY=2;
var _DATE_MNAMED=3;
var _DATE_SMNAMED=4;

var _DATE=null;
var _LARGESTDATE="1/1/2038";
var _TIMEINTERVAL=0.50;
var _NOTIME=9999;
var _TIMELESSROW=-4;
var _TIMELESSROWHEIGHT="15px";
var _ORIGBORDERSTYLE="_O";
var _SUBJECTCOLOR=null;
var _SUBJECTHIGHLIGHTCOLOR=null;
var _CELLBORDERSTYLE=null;
var _CELLBORDERSTYLE2=null;
var _CELLBORDERSTYLE3=null;
var _TIMELESSBOTTOMBORDER=null;
var _CELLBORDERHIGHLIGHTSTYLE=null;
var _CELLBORDERHIGHLIGHTCOLOR=null;
var _TABLEBORDERSTYLE=null;
var _TITLEBARCOLOR=null;
var _TITLEBARHIGHLIGHTCOLOR=null;
var _CLOSEAREACOLOR=null;
var _HEADERCOLOR=null;
var _DARKERHEADERCOLOR=null;
var _HEADERHIGHLIGHTCOLOR=null;
var _HEADERBORDERSTYLE=null;
var _TEXTCOLOR=null;
var _TEXTHIGHLIGHTCOLOR=null;
var _DIVHIGHLIGHTCOLOR=null;
var _DIVCOLOR=null;
var _BUTTONCOLOR=null;
var _BUTTONHIGHLIGHTCOLOR=null;
var _EDITBOXBGCOLOR=null;
var _USERFONT;
var _SMALLFONTSIZE;
var _MEDIUMFONTSIZE;
var _LARGEFONTSIZE;
var _TIMEFONTSIZE;
var _DAYFONTSIZE;
var _EVENT_PRIVACY_DEFAULT=0;
var _CALENDAR_PINUPS="";

function setPrefs()
{
	_CLOCK=_24HOURCLOCK;
	_DATE=_DATE_MNAMED;
	_SUBJECTCOLOR="#000000";
	_SUBJECTHIGHLIGHTCOLOR="#0000FF";
	_CELLBORDERSTYLE="1px solid #C1C1C1";
	_CELLBORDERSTYLE3="1px solid #D9D9D9";
	_CELLBORDERSTYLE2="1px dotted #C1C1C1";
	_TIMELESSBOTTOMBORDER="0px solid #222222";
	_CELLBORDERHIGHLIGHTSTYLE="1px solid #FFAE00";
	_CELLBORDERHIGHLIGHTCOLOR="#FFAE00";
	_TABLEBORDERSTYLE="1px solid #000000";
	_TITLEBARCOLOR="#E6E6E6";
	_TITLEBARHIGHLIGHTCOLOR="#90BCF8";
	_CLOSEAREACOLOR="#FFA0F7";
	_HEADERCOLOR="#C3D9FF";
	_HEADERHIGHLIGHTCOLOR="#BCFAFF";
	_DARKERHEADERCOLOR="#C3D9FF"
	_HEADERBORDERSTYLE="1px solid "+_HEADERCOLOR;
	_TEXTCOLOR="#000000";
	_TEXTHIGHLIGHTCOLOR="#888888";
	_DIVHIGHLIGHTCOLOR="#E6E6E6";
	_DIVCOLOR="#FFFFFF";
	_USERFONT="Arial";
	_SMALLFONTSIZE="12px";
	_MEDIUMFONTSIZE="12px";
	_LARGEFONTSIZE="12px";
	_TIMEFONTSIZE="12px";
	_DAYFONTSIZE="12px";
	_BUTTONCOLOR="#CDEAF5";
	_BUTTONHIGHLIGHTCOLOR="#E6E6E6";
	_EDITBOXBGCOLOR="#FFFFFF";
}
